//сюда не смотреть - это должно выводиться с сервера)
const products = [
    {
        title: 'New York Стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_1.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1200,
        price: 1200,
    },
    {
        title: 'New York Премиум',
        img: 'storage/uploads/img_cheesecakes/cake_2.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1100,
    },
    {
        title: 'Шоколадный презент',
        img: 'storage/uploads/img_cheesecakes/cake_3.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1400,
        price: 1300,
    },
    {
        title: 'Шоколадный Стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_4.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1500,
        price: 1100,
    },
    {
        title: 'Шоколадный Премиум',
        img: 'storage/uploads/img_cheesecakes/cake_5.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Карамельный с арахисом',
        img: 'storage/uploads/img_cheesecakes/cake_6.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1400,
    },
    {
        title: 'New York с малиной стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_7.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1500,
        price: 1300,
    },
    {
        title: 'New York с малиной Премиум',
        img: 'storage/uploads/img_cheesecakes/cake_8.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 900,
    },
    {
        title: 'New York с клубникой презент',
        img: 'storage/uploads/img_cheesecakes/cake_9.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 900,
        price: 1300,
    },
    {
        title: 'New York с клубникой Стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_10.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 800,
        price: 1300,
    },
    {
        title: 'New York с клубникой Премиум',
        img: 'storage/uploads/img_cheesecakes/cake_11.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Фитнес Микс',
        img: 'storage/uploads/img_cheesecakes/cake_12.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1099,
    },
    {
        title: 'Шоколадно-ореховый микс',
        img: 'storage/uploads/img_cheesecakes/cake_13.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1300,
    },
    {
        title: 'Фруктовый микс',
        img: 'storage/uploads/img_cheesecakes/cake_14.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1400,
        price: 1100,
    },
    {
        title: 'New York с черникой стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_15.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1600,
        price: 2100,
    },
    {
        title: 'New York с лесными ягодами презент',
        img: 'storage/uploads/img_cheesecakes/cake_16.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1500,
    },
    {
        title: 'Яблочный Презент',
        img: 'storage/uploads/img_cheesecakes/cake_17.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Ореховый Презент',
        img: 'storage/uploads/img_cheesecakes/cake_18.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1300,
    },
    {
        title: 'New York с вишней Стандарт',
        img: 'storage/uploads/img_cheesecakes/cake_19.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1200,
        price: 1300,
    },
    {
        title: 'Ассорти Premium Cheeseberry',
        img: 'storage/uploads/img_cheesecakes/cake_20.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
]
export default products;
