//сюда не смотреть - это должно выводиться с сервера)
const products = [
    {
        title: 'Чизкейк "New York Стандарт"',
        img: '/img_cheesecakes/cake_1.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1200,
        price: 1200,
    },
    {
        title: 'Чизкейк «New York Премиум»',
        img: '/img_cheesecakes/cake_2.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1100,
    },
    {
        title: 'Чизкейк «Шоколадный презент»',
        img: '/img_cheesecakes/cake_3.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1400,
        price: 1300,
    },
    {
        title: 'Чизкейк «Шоколадный Стандарт»',
        img: '/img_cheesecakes/cake_4.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1500,
        price: 1100,
    },
    {
        title: 'Чизкейк «Шоколадный Премиум»',
        img: '/img_cheesecakes/cake_5.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Чизкейк «Карамельный с арахисом»',
        img: '/img_cheesecakes/cake_6.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1400,
    },
    {
        title: 'Чизкейк «New York с малиной стандарт»',
        img: '/img_cheesecakes/cake_7.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1500,
        price: 1300,
    },
    {
        title: 'Чизкейк «New York с малиной Премиум»',
        img: '/img_cheesecakes/cake_8.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 900,
    },
    {
        title: 'Чизкейк «New York с клубникой презент»',
        img: '/img_cheesecakes/cake_9.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 900,
        price: 1300,
    },
    {
        title: 'Чизкейк «New York с клубникой Стандарт»',
        img: '/img_cheesecakes/cake_10.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 800,
        price: 1300,
    },
    {
        title: 'Чизкейк «New York с клубникой Премиум»',
        img: '/img_cheesecakes/cake_11.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Чизкейк Фитнес Микс',
        img: '/img_cheesecakes/cake_12.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1099,
    },
    {
        title: 'Чизкейк Шоколадно-ореховый микс',
        img: '/img_cheesecakes/cake_13.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1300,
    },
    {
        title: 'Чизкейк Фруктовый микс',
        img: '/img_cheesecakes/cake_14.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1400,
        price: 1100,
    },
    {
        title: 'Чизкейк «New York с черникой стандарт»',
        img: '/img_cheesecakes/cake_15.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1600,
        price: 2100,
    },
    {
        title: 'Чизкейк «New York с лесными ягодами презент»',
        img: '/img_cheesecakes/cake_16.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1500,
    },
    {
        title: 'Чизкейк «Яблочный Презент»',
        img: '/img_cheesecakes/cake_17.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
    {
        title: 'Чизкейк «Ореховый Презент»',
        img: '/img_cheesecakes/cake_18.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1300,
        price: 1300,
    },
    {
        title: 'Чизкейк «New York с вишней Стандарт»',
        img: '/img_cheesecakes/cake_19.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1200,
        price: 1300,
    },
    {
        title: 'Чизкейк «Ассорти Premium Cheeseberry»',
        img: '/img_cheesecakes/cake_20.jpg',
        description: 'Какой то текс описывающий тортик',
        mass: 1100,
        price: 1500,
    },
]
export default products;